server.port=${PORT:8080}
management.endpoints.web.exposure.include=health
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${JDBC_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
